name: Build debug APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: HeliBoard-debug
          path: app/build/outputs/apk/debug/*-debug*.apk

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v5
        with:
          name: reports
          path: '*/build/reports'
          if-no-files-found: ignore
        if: ${{ failure() }}
